# Telegram token
telegram-token: telegram-token

# Bot service
secret: random-string
allowed-usernames:
  - just
  - allowed
  - users
db-host: mongo
db-port: 27017

# Daemon service
bot-url: url-to-bot-host
player-interval:
  - 5
  - 30
borders:
  from:
    - 7
    - 00
  to:
    - 22
    - 00