version: "3.3"

networks:
  app-tier:
    driver: bridge

services:  
  bot:  
    build: .
    restart: always
    ports: 
      - 8080:8080
    networks:
      - app-tier
    depends_on:
      - mongo

  mongo:
    image: "mongo:latest"
    restart: always
    networks:
      - app-tier
